# -*- coding: utf-8 -*-
"""
Created on Wed Dec 20 15:56:20 2017

@author: matth
"""

import tkinter as tk
import Board
import Block



    
#have a predefined array of different bArrays that correspond to different pieces
        #these bArrays will have one reference block, then, the other blocks will be set off of that block's position
        #these initial conditions are set once
        #these will be generated by a random generator function
#the piece class will store these arrays into a piece object
        #the piece class will have a rotation method and movement methods
class Piece(object):
    def __init__(self,bArr):
        self.p = bArr
    def cW(self):
        #every piece will move in a 
        pass
    def ccW(self):
        pass
        
        
root = tk.Tk()
app = Board.Board(400,800,master = root)
b = Block.Block([5,6],1)
print(b.getPos())
app.placeBlock(b)
app.drawBoard()
b.mR(app)
app.placeBlock(b)
app.drawBoard()
app.mainloop()